// --------------------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>// 
// <copyright file="dbgenENUM.cs" company="EvePanix">
//   Copyright (c) Jedzia 2001-2015, EvePanix. All rights reserved. See the license notes shipped with this source and the GNU GPL.
// </copyright>
//  <author>Jedzia</author>
//  <email>jed69@gmx.de</email>
//  <date>28.07.2015 11:54</date>
// <summary>
//   This enumeration contains the items contained in the table Sheet1
// </summary>
// --------------------------------------------------------------------------------------------------------------------
namespace Deveknife.Blades.FileManager.Jobs.Compression
{
    using System;

    /// <summary>
    /// This enumeration contains the items contained in the table Sheet1
    /// </summary>
    [Serializable]
    public class Sheet1
    {
        /// Alphabetic switches list->-rr[N]
        /// Description->add data recovery record
        /// <summary> 
        /// add_data_recovery_record
        /// </summary>
        public const string add_data_recovery_record = "-rr[N]";

        /// Alphabetic switches list->-ao
        /// Description->add files with Archive attribute set
        /// <summary> 
        /// add_files_with_Archive_attribute_set
        /// </summary>
        public const string add_files_with_Archive_attribute_set = "-ao";

        /// Alphabetic switches list->-qo[-|+]
        /// Description->add quick open information [none|force]
        /// <summary> 
        /// add_quick_open_information_none_force
        /// </summary>
        public const string add_quick_open_information_none_force = "-qo[-|+]";

        /// Alphabetic switches list->-n<file>
        /// Description->additionally filter included files
        /// <summary> 
        /// additionally_filter_included_files
        /// </summary>
        public const string additionally_filter_included_files = "-n<file>";

        /// Alphabetic switches list->-ad
        /// Description->append archive name to destination path
        /// <summary> 
        /// append_archive_name_to_destination_path
        /// </summary>
        public const string append_archive_name_to_destination_path = "-ad";

        /// Alphabetic switches list->-y
        /// Description->assume Yes on all queries
        /// <summary> 
        /// assume_Yes_on_all_queries
        /// </summary>
        public const string assume_Yes_on_all_queries = "-y";

        /// Alphabetic switches list->-ac
        /// Description->clear Archive attribute after compression or extraction
        /// <summary> 
        /// clear_Archive_attribute_after_compression_or_extraction
        /// </summary>
        public const string clear_Archive_attribute_after_compression_or_extraction = "-ac";

        /// Alphabetic switches list->-cl
        /// Description->convert file names to lower case
        /// <summary> 
        /// convert_file_names_to_lower_case
        /// </summary>
        public const string convert_file_names_to_lower_case = "-cl";

        /// Alphabetic switches list->-cu
        /// Description->convert file names to upper case
        /// <summary> 
        /// convert_file_names_to_upper_case
        /// </summary>
        public const string convert_file_names_to_upper_case = "-cu";

        /// Alphabetic switches list->-s
        /// Description->create a solid archive
        /// <summary> 
        /// create_a_solid_archive
        /// </summary>
        public const string create_a_solid_archive = "-s";

        /// Alphabetic switches list->-sv-
        /// Description->create dependent solid volumes
        /// <summary> 
        /// create_dependent_solid_volumes
        /// </summary>
        public const string create_dependent_solid_volumes = "-sv-";

        /// Alphabetic switches list->-sv
        /// Description->create independent solid volumes
        /// <summary> 
        /// create_independent_solid_volumes
        /// </summary>
        public const string create_independent_solid_volumes = "-sv";

        /// Alphabetic switches list->-rv[N]
        /// Description->create recovery volumes
        /// <summary> 
        /// create_recovery_volumes
        /// </summary>
        public const string create_recovery_volumes = "-rv[N]";

        /// Alphabetic switches list->-sfx[name]
        /// Description->create self-extracting archive
        /// <summary> 
        /// create_self_extracting_archive
        /// </summary>
        public const string create_self_extracting_archive = "-sfx[name]";

        /// Alphabetic switches list->-s<N>
        /// Description->create solid groups using file count
        /// <summary> 
        /// create_solid_groups_using_file_count
        /// </summary>
        public const string create_solid_groups_using_file_count = "-s<N>";

        /// Alphabetic switches list->-se
        /// Description->create solid groups using file extension
        /// <summary> 
        /// create_solid_groups_using_file_extension
        /// </summary>
        public const string create_solid_groups_using_file_extension = "-se";

        /// Alphabetic switches list->-v<n>[k|b|f|m|M|g|G] 
        /// Description->create volumes
        /// <summary> 
        /// create_volumes
        /// </summary>
        public const string create_volumes = "-v<n>[k|b|f|m|M|g|G] ";

        /// Alphabetic switches list->-df
        /// Description->delete files after archiving
        /// <summary> 
        /// delete_files_after_archiving
        /// </summary>
        public const string delete_files_after_archiving = "-df";

        /// Alphabetic switches list->-dr
        /// Description->delete files to Recycle Bin
        /// <summary> 
        /// delete_files_to_Recycle_Bin
        /// </summary>
        public const string delete_files_to_Recycle_Bin = "-dr";

        /// Alphabetic switches list->-@[+]
        /// Description->disable [enable] file lists
        /// <summary> 
        /// disable_enable_file_lists
        /// </summary>
        public const string disable_enable_file_lists = "-@[+]";

        /// Alphabetic switches list->-inul
        /// Description->disable error messages
        /// <summary> 
        /// disable_error_messages
        /// </summary>
        public const string disable_error_messages = "-inul";

        /// Alphabetic switches list->-r-
        /// Description->disable recursion
        /// <summary> 
        /// disable_recursion
        /// </summary>
        public const string disable_recursion = "-r-";

        /// Alphabetic switches list->-s-
        /// Description->disable solid archiving
        /// <summary> 
        /// disable_solid_archiving
        /// </summary>
        public const string disable_solid_archiving = "-s-";

        /// Alphabetic switches list->-ed
        /// Description->do not add empty folders
        /// <summary> 
        /// do_not_add_empty_folders
        /// </summary>
        public const string do_not_add_empty_folders = "-ed";

        /// Alphabetic switches list->-en
        /// Description->do not add "end of archive" block
        /// <summary> 
        /// do_not_add_end_of_archive_block
        /// </summary>
        public const string do_not_add_end_of_archive_block = "-en";

        /// Alphabetic switches list->-ds
        /// Description->do not sort archiving files
        /// <summary> 
        /// do_not_sort_archiving_files
        /// </summary>
        public const string do_not_sort_archiving_files = "-ds";

        /// Alphabetic switches list->-hp[pwd]
        /// Description->encrypt both file data and headers
        /// <summary> 
        /// encrypt_both_file_data_and_headers
        /// </summary>
        public const string encrypt_both_file_data_and_headers = "-hp[pwd]";

        /// Alphabetic switches list->-vd
        /// Description->erase disk contents before creating volume
        /// <summary> 
        /// erase_disk_contents_before_creating_volume
        /// </summary>
        public const string erase_disk_contents_before_creating_volume = "-vd";

        /// Alphabetic switches list->0
        /// Description->exclude base folder from names
        /// <summary> 
        /// exclude_base_folder_from_names
        /// </summary>
        public const string exclude_base_folder_from_names = "0";

        /// Alphabetic switches list->-x@<listfile>
        /// Description->exclude files listed in the specified list file
        /// <summary> 
        /// exclude_files_listed_in_the_specified_list_file
        /// </summary>
        public const string exclude_files_listed_in_the_specified_list_file = "-x@<listfile>";

        /// Alphabetic switches list->-ep
        /// Description->exclude paths from names
        /// <summary> 
        /// exclude_paths_from_names
        /// </summary>
        public const string exclude_paths_from_names = "-ep";

        /// Alphabetic switches list->-x<file>
        /// Description->exclude the specified file
        /// <summary> 
        /// exclude_the_specified_file
        /// </summary>
        public const string exclude_the_specified_file = "-x<file>";

        /// Alphabetic switches list->#REF!
        /// Description->expand paths to full
        /// <summary> 
        /// expand_paths_to_full
        /// </summary>
        public const string expand_paths_to_full = "#REF!";

        /// Alphabetic switches list->#REF!
        /// Description->expand paths to full including the drive letter
        /// <summary> 
        /// expand_paths_to_full_including_the_drive_letter
        /// </summary>
        public const string expand_paths_to_full_including_the_drive_letter = "#REF!";

        /// Alphabetic switches list->-ver[n]
        /// Description->file version control
        /// <summary> 
        /// file_version_control
        /// </summary>
        public const string file_version_control = "-ver[n]";

        /// Alphabetic switches list->-f
        /// Description->freshen files
        /// <summary> 
        /// freshen_files
        /// </summary>
        public const string freshen_files = "-f";

        /// Alphabetic switches list->-ag[format]
        /// Description->generate archive name using the current date and time
        /// <summary> 
        /// generate_archive_name_using_the_current_date_and_time
        /// </summary>
        public const string generate_archive_name_using_the_current_date_and_time = "-ag[format]";

        /// Alphabetic switches list->-cfg-
        /// Description->ignore default profile and environment variable
        /// <summary> 
        /// ignore_default_profile_and_environment_variable
        /// </summary>
        public const string ignore_default_profile_and_environment_variable = "-cfg-";

        /// Alphabetic switches list->-ai
        /// Description->ignore file attributes
        /// <summary> 
        /// ignore_file_attributes
        /// </summary>
        public const string ignore_file_attributes = "-ai";

        /// Alphabetic switches list->-kb
        /// Description->keep broken extracted files
        /// <summary> 
        /// keep_broken_extracted_files
        /// </summary>
        public const string keep_broken_extracted_files = "-kb";

        /// Alphabetic switches list->-tk
        /// Description->keep original archive time
        /// <summary> 
        /// keep_original_archive_time
        /// </summary>
        public const string keep_original_archive_time = "-tk";

        /// Alphabetic switches list->-k
        /// Description->lock archive
        /// <summary> 
        /// lock_archive
        /// </summary>
        public const string lock_archive = "-k";

        /// Alphabetic switches list->-ilog[name]
        /// Description->log errors to file
        /// <summary> 
        /// log_errors_to_file
        /// </summary>
        public const string log_errors_to_file = "-ilog[name]";

        /// Alphabetic switches list->-dh
        /// Description->open shared files
        /// <summary> 
        /// open_shared_files
        /// </summary>
        public const string open_shared_files = "-dh";

        /// Alphabetic switches list->-vp
        /// Description->pause before each volume
        /// <summary> 
        /// pause_before_each_volume
        /// </summary>
        public const string pause_before_each_volume = "-vp";

        /// Alphabetic switches list->-ow
        /// Description->process file security information
        /// <summary> 
        /// process_file_security_information
        /// </summary>
        public const string process_file_security_information = "-ow";

        /// Alphabetic switches list->-ta<date>
        /// Description->process files modified after the specified date
        /// <summary> 
        /// process_files_modified_after_the_specified_date
        /// </summary>
        public const string process_files_modified_after_the_specified_date = "-ta<date>";

        /// Alphabetic switches list->-tb<date>
        /// Description->process files modified before the specified date
        /// <summary> 
        /// process_files_modified_before_the_specified_date
        /// </summary>
        public const string process_files_modified_before_the_specified_date = "-tb<date>";

        /// Alphabetic switches list->-tn<time>
        /// Description->process files newer than the specified time
        /// <summary> 
        /// process_files_newer_than_the_specified_time
        /// </summary>
        public const string process_files_newer_than_the_specified_time = "-tn<time>";

        /// Alphabetic switches list->-to<time>
        /// Description->process files older than the specified time
        /// <summary> 
        /// process_files_older_than_the_specified_time
        /// </summary>
        public const string process_files_older_than_the_specified_time = "-to<time>";

        /// Alphabetic switches list->-sl<size>
        /// Description->process files with size less than specified
        /// <summary> 
        /// process_files_with_size_less_than_specified
        /// </summary>
        public const string process_files_with_size_less_than_specified = "-sl<size>";

        /// Alphabetic switches list->-sm<size>
        /// Description->process files with size more than specified
        /// <summary> 
        /// process_files_with_size_more_than_specified
        /// </summary>
        public const string process_files_with_size_more_than_specified = "-sm<size>";

        /// Alphabetic switches list->-n@<listfile>
        /// Description->read additional filter masks from list file
        /// <summary> 
        /// read_additional_filter_masks_from_list_file
        /// </summary>
        public const string read_additional_filter_masks_from_list_file = "-n@<listfile>";

        /// Alphabetic switches list->-z<file>
        /// Description->read archive comment from file
        /// <summary> 
        /// read_archive_comment_from_file
        /// </summary>
        public const string read_archive_comment_from_file = "-z<file>";

        /// Alphabetic switches list->-r
        /// Description->recurse subfolders
        /// <summary> 
        /// recurse_subfolders
        /// </summary>
        public const string recurse_subfolders = "-r";

        /// Alphabetic switches list->-r0
        /// Description->recurse subfolders for wildcard names only
        /// <summary> 
        /// recurse_subfolders_for_wildcard_names_only
        /// </summary>
        public const string recurse_subfolders_for_wildcard_names_only = "-r0";

        /// Alphabetic switches list->-or
        /// Description->rename files automatically
        /// <summary> 
        /// rename_files_automatically
        /// </summary>
        public const string rename_files_automatically = "-or";

        /// Alphabetic switches list->-iadm
        /// Description->request administrative access for SFX archive
        /// <summary> 
        /// request_administrative_access_for_SFX_archive
        /// </summary>
        public const string request_administrative_access_for_SFX_archive = "-iadm";

        /// Alphabetic switches list->-ibck
        /// Description->run WinRAR in background
        /// <summary> 
        /// run_WinRAR_in_background
        /// </summary>
        public const string run_WinRAR_in_background = "-ibck";

        /// Alphabetic switches list->-oh
        /// Description->save hard links as the link instead of the file
        /// <summary> 
        /// save_hard_links_as_the_link_instead_of_the_file
        /// </summary>
        public const string save_hard_links_as_the_link_instead_of_the_file = "-oh";

        /// Alphabetic switches list->-oi[-]
        /// Description->save identical files as references
        /// <summary> 
        /// save_identical_files_as_references
        /// </summary>
        public const string save_identical_files_as_references = "-oi[-]";

        /// Alphabetic switches list->-os
        /// Description->save NTFS streams
        /// <summary> 
        /// save_NTFS_streams
        /// </summary>
        public const string save_NTFS_streams = "-os";

        /// Alphabetic switches list->-ts<m,c,a>
        /// Description->save or restore file time (modification, creation, access)
        /// <summary> 
        /// save_or_restore_file_time_modification_creation_access
        /// </summary>
        public const string save_or_restore_file_time_modification_creation_access = "-ts<m,c,a>";

        /// Alphabetic switches list->-ol
        /// Description->save symbolic links as the link instead of the file
        /// <summary> 
        /// save_symbolic_links_as_the_link_instead_of_the_file
        /// </summary>
        public const string save_symbolic_links_as_the_link_instead_of_the_file = "-ol";

        /// Alphabetic switches list->-cp<name>
        /// Description->select a compression profile
        /// <summary> 
        /// select_a_compression_profile
        /// </summary>
        public const string select_a_compression_profile = "-cp<name>";

        /// Alphabetic switches list->-md<n>
        /// Description->select dictionary size
        /// <summary> 
        /// select_dictionary_size
        /// </summary>
        public const string select_dictionary_size = "-md<n>";

        /// Alphabetic switches list->-ht[b|c]
        /// Description->select hash type [BLAKE2,CRC32] for file checksum
        /// <summary> 
        /// select_hash_type_BLAKE2_CRC32_for_file_checksum
        /// </summary>
        public const string select_hash_type_BLAKE2_CRC32_for_file_checksum = "-ht[b|c]";

        /// Alphabetic switches list->-ieml[.][addr]
        /// Description->send archive by email
        /// <summary> 
        /// send_archive_by_email
        /// </summary>
        public const string send_archive_by_email = "-ieml[.][addr]";

        /// Alphabetic switches list->-mc<par>
        /// Description->set advanced compression parameters
        /// <summary> 
        /// set_advanced_compression_parameters
        /// </summary>
        public const string set_advanced_compression_parameters = "-mc<par>";

        /// Alphabetic switches list->-tl
        /// Description->set archive time to newest file
        /// <summary> 
        /// set_archive_time_to_newest_file
        /// </summary>
        public const string set_archive_time_to_newest_file = "-tl";

        /// Alphabetic switches list->-m<n>
        /// Description->set compression method
        /// <summary> 
        /// set_compression_method
        /// </summary>
        public const string set_compression_method = "-m<n>";

        /// Alphabetic switches list->-e[+]<attr>
        /// Description->set file exclude or include attributes
        /// <summary> 
        /// set_file_exclude_or_include_attributes
        /// </summary>
        public const string set_file_exclude_or_include_attributes = "-e[+]<attr>";

        /// Alphabetic switches list->-w<path>
        /// Description->set folder for temporary files
        /// <summary> 
        /// set_folder_for_temporary_files
        /// </summary>
        public const string set_folder_for_temporary_files = "-w<path>";

        /// Alphabetic switches list->-oc
        /// Description->set NTFS "Compressed" attribute
        /// <summary> 
        /// set_NTFS_Compressed_attribute
        /// </summary>
        public const string set_NTFS_Compressed_attribute = "-oc";

        /// Alphabetic switches list->-p[pwd]
        /// Description->set password
        /// <summary> 
        /// set_password
        /// </summary>
        public const string set_password = "-p[pwd]";

        /// Alphabetic switches list->-ap<path>
        /// Description->set path inside archive
        /// <summary> 
        /// set_path_inside_archive
        /// </summary>
        public const string set_path_inside_archive = "-ap<path>";

        /// Alphabetic switches list->-ri
        /// Description->set priority and sleep time
        /// <summary> 
        /// set_priority_and_sleep_time
        /// </summary>
        public const string set_priority_and_sleep_time = "-ri";

        /// Alphabetic switches list->-mt<threads>
        /// Description->set the number of threads
        /// <summary> 
        /// set_the_number_of_threads
        /// </summary>
        public const string set_the_number_of_threads = "-mt<threads>";

        /// Alphabetic switches list->-o[+|-]
        /// Description->set the overwrite mode
        /// <summary> 
        /// set_the_overwrite_mode
        /// </summary>
        public const string set_the_overwrite_mode = "-o[+|-]";

        /// Alphabetic switches list->-ma[4|5]
        /// Description->specify a version of archiving format
        /// <summary> 
        /// specify_a_version_of_archiving_format
        /// </summary>
        public const string specify_a_version_of_archiving_format = "-ma[4|5]";

        /// Alphabetic switches list->-af<type>
        /// Description->specify archive format
        /// <summary> 
        /// specify_archive_format
        /// </summary>
        public const string specify_archive_format = "-af<type>";

        /// Alphabetic switches list->-ms[list]
        /// Description->specify file types to store
        /// <summary> 
        /// specify_file_types_to_store
        /// </summary>
        public const string specify_file_types_to_store = "-ms[list]";

        /// Alphabetic switches list->-iicon<name>
        /// Description->specify SFX icon
        /// <summary> 
        /// specify_SFX_icon
        /// </summary>
        public const string specify_SFX_icon = "-iicon<name>";

        /// Alphabetic switches list->-iimg<name>
        /// Description->specify SFX logo
        /// <summary> 
        /// specify_SFX_logo
        /// </summary>
        public const string specify_SFX_logo = "-iimg<name>";

        /// Alphabetic switches list->-sc<charset>[objects]
        /// Description->specify the character set
        /// <summary> 
        /// specify_the_character_set
        /// </summary>
        public const string specify_the_character_set = "-sc<charset>[objects]";

        /// Alphabetic switches list->--
        /// Description->stop switches scanning
        /// <summary> 
        /// stop_switches_scanning
        /// </summary>
        public const string stop_switches_scanning = "--";

        /// Alphabetic switches list->-as
        /// Description->synchronize archive contents
        /// <summary> 
        /// synchronize_archive_contents
        /// </summary>
        public const string synchronize_archive_contents = "-as";

        /// Alphabetic switches list->-t
        /// Description->test files after archiving
        /// <summary> 
        /// test_files_after_archiving
        /// </summary>
        public const string test_files_after_archiving = "-t";

        /// Alphabetic switches list->-ioff
        /// Description->turn PC off
        /// <summary> 
        /// turn_PC_off
        /// </summary>
        public const string turn_PC_off = "-ioff";

        /// Alphabetic switches list->-u
        /// Description->update files
        /// <summary> 
        /// update_files
        /// </summary>
        public const string update_files = "-u";

        /// Alphabetic switches list->-vn
        /// Description->use the old style volume naming scheme
        /// <summary> 
        /// use_the_old_style_volume_naming_scheme
        /// </summary>
        public const string use_the_old_style_volume_naming_scheme = "-vn";

        /// Alphabetic switches list->-dw
        /// Description->wipe files after archiving
        /// <summary> 
        /// wipe_files_after_archiving
        /// </summary>
        public const string wipe_files_after_archiving = "-dw";

        /// Alphabetic switches list->-log[fmt][=name]
        /// Description->write names to log file
        /// <summary> 
        /// write_names_to_log_file
        /// </summary>
        public const string write_names_to_log_file = "-log[fmt][=name]";
    }
}